### ISSUE TITLE
Display certain

### ISSUE THREAD

**Issue by abjaf** [thomasvaeth/instafetch.js#2]
Hey is there anyway to only display images with a certain hashtag? I've tried tagName and tag parameters but doesn't seem to help. New to js so not sure how to get it to work with hashtags. 

Thanks for this amazing plugin by the way! As I said i'm a newbie when it comes to js but still got it to work within minutes!

**Comment by thomasvaeth** [comment]
Nah. It does only what it was built to do, which is pull recent images from your feed. Hashtags are a completely different endpoint if you read through the Instagram API docs.
