### ISSUE TITLE
caption: true causes to fail

### ISSUE THREAD

**Issue by secretgspot** [thomasvaeth/instafetch.js#4]
instafetch.min.js:1 TypeError: Cannot read property 'text' of null
    at instafetch.min.js:1
    at Array.forEach (<anonymous>)
    at E (instafetch.min.js:1)
    at instafetch.min.js:1
    at <anonymous>

instagram account doesn't contain caption text on images, might be the reason why it fails.

**Comment by thomasvaeth** [comment]
The Instagram API returns null for data.caption if there is no caption. I added to the if statement that checks if the user even wants to display a caption. Everything should be all good now.
