### ISSUE TITLE
Is it possible to change the default image size being loaded?

### ISSUE THREAD

**Issue by solbreslin** [thomasvaeth/instafetch.js#5]
By default, instafetch appears to load images 640 x 640 px. I have created a gallery that displays images at approx 200 x 200. 

Is there a way to load a smaller image size?

Thanks.

**Comment by thomasvaeth** [comment]
You can search the script for `standard_resolution` and switch it to `thumbnail` or `low_resolution`. You can't use the CDN, but you'll get the resolution you want. https://www.instagram.com/developer/endpoints/users/
