### ISSUE TITLE
load complete callback

### ISSUE THREAD

**Issue by toddpadwick** [thomasvaeth/instafetch.js#6]
Hi, 
Nice simple plugin :)

I am using the instafetch plugin with a flickity.js slider plugin. So I need to query when the feed has loaded, to then trigger the carousel plugin to initiate. 
Is there an event for this or a good way to query?

Cheers

**Comment by thomasvaeth** [comment]
I am not familiar with that one since I mostly use Owl. Owl has custom events to initialize the carousel, so my guess is you're going to have to edit the source code to use a custom event in the `displayFeed` function.
